### ISSUE TITLE
Add a tsconfig.json file at the root of the monorepo

### ISSUE THREAD

**Issue by patricklafrance** [workleap/wl-foundry-cli#10]
There should be a `tsconfig.json` file using `@workleap/typescript-config/monorepo-root.json` configs at the root of the project.

**Comment by alexasselin008** [comment]
What is the use case for this tsconfig? it's not in charge of linting anything?

**Comment by patricklafrance** [comment]
Lint root files. What does `@workleap/typescript-config/monorepo-root.json` is intended to be used for otherwise?

**Comment by ofrogon** [comment]
Was accomplish 2 weeks ago in PR #20
