### ISSUE TITLE
We should add input validation to both CLIs

### ISSUE THREAD

**Issue by alexasselin008** [workleap/wl-foundry-cli#11]
At the moment, there is no validation on the following fields: 
- outputDirectory
- packageScope
- hostScope

The output directory doesn't really need validation, but we could make sure the path entered is composed of valid characters

However, i think package scope and host scope should have validation to ensure they: 
 - start with a @
 - do not end with /
 - the regex pattern for package.json name is this: `^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$` maybe we can use this

**Comment by patricklafrance** [comment]
Why both CLIs? That's quite redondant as we don't expect any users to directly call the `foundry` CLI.

Sometimes defensive programming is good but for most of the thing that we do, most of the time it's noise obscuring the important parts.

**Comment by alexasselin008** [comment]
We expect people to directly use the create-workleap command and we expect people to wrap the foundry cli. 
I understand your concern about defensive programming, but adding input validation on create-workleap would give better error messages to users. Since most error will occur in the underlying cli, some messages might not be as clear. 

Validating input would also help the DevUX of people wrapping the CLI in the future

**Accurate Execution**: Validating inputs ensures that code executes without errors or unexpected behavior.
**User Experience**: Validating inputs improves the user experience by providing clear error messages and making it easier for users to correct their mistakes.
**Efficiency**: Validating inputs optimizes performance and efficiency by avoiding unnecessary computation or resource usage.
**Maintainability**: Validating inputs catches errors early, making code more maintainable and reducing time and effort required for maintenance.

**Comment by patricklafrance** [comment]
My comment is about adding validation to BOTH CLI as it's suggested in the issue title.

💯 agree with you about adding validation to `create-workleap`
