### ISSUE TITLE
❔Decide how to handle versionning in template package.json file

### ISSUE THREAD

**Issue by ofrogon** [workleap/wl-foundry-cli#32]
![image](https://github.com/workleap/wl-foundry-cli/assets/4323800/87e7de3d-8af4-4cac-985a-861aacdbf0b3)

**Comment by alexasselin008** [comment]
I think we could use the `npm-check-updates` package for this. 

Step 1: manually remove all the ^ in the version numbers; 
Step 2: Download the code
Step 3: run `pnpm dlx  npm-check-updates --target minor -u`

Breakdown of the command
`pnpm dlx  npm-check-updates` : run the remote package
`npm-check-updates --target minor -u`: Update the package.json with updated version, but only minors and patchs.  `npm-check-updates --target minor` lists the changes, and -u updates the package.json

**Comment by alexasselin008** [comment]
The cli could probably have a dependency on npm-check-updates and use it with the Module/Programmatic Usage way instead of calling another CLi. 

https://www.npmjs.com/package/npm-check-updates -> Check the "Module/Programmatic Usage" section
